package com.fiscaladmin.joget.transitionguard;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.Map;

import org.joget.apps.app.service.AppUtil;
import org.joget.apps.form.dao.FormDataDao;
import org.joget.apps.form.model.FormRow;
import org.joget.apps.form.model.FormRowSet;
import org.joget.commons.util.LogUtil;
import org.joget.plugin.base.DefaultApplicationPlugin;
import org.joget.workflow.util.WorkflowUtil;

import com.fiscaladmin.joget.statusmanager.InvalidTransitionException;
import com.fiscaladmin.joget.statusmanager.StatusManager;

/**
 * Generic, config-driven lifecycle transition guard. Wired as a form post-submission
 * processor. On save it reads the record's chosen action ({@code actionField}); if set, it
 * looks the action up in the {@code transitions} config, drives
 * {@link StatusManager#apply} (validated against the mmEntityTransition seed), stamps any
 * set-now effect fields (e.g. submitted_at), consumes the action, and saves once. An illegal
 * move is recorded, not applied. Entity/table/status/action/transitions are all properties,
 * generated by the transition-action projector from the L1 model.
 *
 * transitions format: {@code action>toState>nowField1,nowField2 | action2>to2> | ...}
 */
public class TransitionGuard extends DefaultApplicationPlugin {

    private static final String CN = TransitionGuard.class.getName();

    public String getName() { return "Lifecycle Transition Guard"; }
    public String getVersion() { return "1.0.0"; }
    public String getDescription() { return "Drives StatusManager transitions from a form action (generated from the L1 model)."; }
    public String getLabel() { return "Lifecycle Transition Guard"; }
    public String getClassName() { return getClass().getName(); }
    public String getPropertyOptions() {
        return AppUtil.readPluginResource(getClassName(), "/properties/transitionGuard.json", null, true, null);
    }

    public Object execute(Map properties) {
        FormDataDao dao = (FormDataDao) AppUtil.getApplicationContext().getBean("formDataDao");
        if (dao == null) { LogUtil.warn(CN, "formDataDao unavailable"); return null; }
        String actor = WorkflowUtil.getCurrentUsername();
        if (actor == null || actor.isEmpty()) actor = "system";

        String entity = str(properties, "entity");
        String tableName = str(properties, "tableName");
        String statusField = def(str(properties, "statusField"), "status");
        String actionField = def(str(properties, "actionField"), "_action");
        String recordId = str(properties, "recordId");
        if (entity.isEmpty() || tableName.isEmpty() || recordId.isEmpty() || recordId.startsWith("#")) return null;

        FormRow row = dao.load(entity, tableName, recordId);
        if (row == null) return null;
        String action = nz(row.getProperty(actionField));
        if (action.isEmpty()) return null;

        String[] hit = findTransition(str(properties, "transitions"), action);
        if (hit == null) { LogUtil.warn(CN, "no transition for action '" + action + "'"); return null; }
        String target = hit[0];
        String setNowCsv = hit[1];

        String result;
        try {
            new StatusManager(dao).apply(entity, row, statusField, recordId, target,
                    Collections.<String>emptyList(), actor, action);
            if (!setNowCsv.isEmpty()) {
                String now = LocalDateTime.now().toString();
                for (String f : setNowCsv.split(",")) {
                    String fn = f.trim();
                    if (!fn.isEmpty()) row.setProperty(fn, now);
                }
            }
            result = "OK: " + nz(row.getProperty(statusField));
        } catch (InvalidTransitionException e) {
            result = "REJECTED: " + e.getMessage();
        } catch (Exception e) {
            result = "ERROR: " + e.getMessage();
            LogUtil.error(CN, e, "transition failed for " + entity + " " + recordId);
        }
        row.setProperty(actionField, "");
        row.setProperty("transition_result", result);
        FormRowSet set = new FormRowSet();
        set.add(row);
        dao.saveOrUpdate(entity, tableName, set);
        LogUtil.info(CN, entity + " " + recordId + " action=" + action + " -> " + result);
        return null;
    }

    /** returns [toState, setNowCsv] for the matching action, or null. */
    private String[] findTransition(String cfg, String action) {
        if (cfg == null) return null;
        for (String seg : cfg.split("\\|")) {
            String[] p = seg.split(">", -1);
            if (p.length >= 2 && action.equals(p[0].trim())) {
                return new String[]{p[1].trim(), p.length > 2 ? p[2].trim() : ""};
            }
        }
        return null;
    }

    private static String str(Map p, String k) { Object v = p.get(k); return v == null ? "" : v.toString(); }
    private static String def(String v, String d) { return v == null || v.isEmpty() ? d : v; }
    private static String nz(String s) { return s == null ? "" : s; }
}
