package com.fiscaladmin.joget.transitionguard;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import org.joget.apps.app.model.AppDefinition;
import org.joget.apps.app.service.AppUtil;
import org.joget.workflow.model.WorkflowProcessResult;
import org.joget.workflow.model.service.WorkflowManager;
import org.joget.apps.form.dao.FormDataDao;
import org.joget.apps.form.model.FormRow;
import org.joget.apps.form.model.FormRowSet;
import org.joget.commons.util.LogUtil;
import org.joget.plugin.base.DefaultApplicationPlugin;
import org.joget.workflow.util.WorkflowUtil;

import com.fiscaladmin.joget.statusmanager.InvalidTransitionException;
import com.fiscaladmin.joget.statusmanager.StatusManager;

/**
 * Generic, config-driven lifecycle transition guard. Wired as a form post-submission
 * processor. On save it reads the record's chosen action ({@code actionField}); if set, it
 * looks the action up in the {@code transitions} config, drives
 * {@link StatusManager#apply} (validated against the mmEntityTransition seed), stamps any
 * set-now effect fields (e.g. submitted_at), consumes the action, and saves once. An illegal
 * move is recorded, not applied. Entity/table/status/action/transitions are all properties,
 * generated by the transition-action projector from the L1 model.
 *
 * transitions format: {@code action>toState>nowField1,nowField2 | action2>to2> | ...}
 */
public class TransitionGuard extends DefaultApplicationPlugin {

    private static final String CN = TransitionGuard.class.getName();

    /**
     * This bundle's own event carrier. Named here, not set process-wide from the
     * Activator: joget-event-chain is a shared library bundle, and a static default
     * set at bundle start re-aims every other consumer in the same JVM.
     */
    static final String EVENT_FORM = "statusEvent";
    private static final DateTimeFormatter TS = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public String getName() { return "Lifecycle Transition Guard"; }
    public String getVersion() { return "1.0.0"; }
    public String getDescription() { return "Drives StatusManager transitions from a form action (generated from the L1 model)."; }
    public String getLabel() { return "Lifecycle Transition Guard"; }
    public String getClassName() { return getClass().getName(); }
    public String getPropertyOptions() {
        return AppUtil.readPluginResource(getClassName(), "/properties/transitionGuard.json", null, true, null);
    }

    public Object execute(Map properties) {
        FormDataDao dao = (FormDataDao) AppUtil.getApplicationContext().getBean("formDataDao");
        if (dao == null) { LogUtil.warn(CN, "formDataDao unavailable"); return null; }
        String actor = WorkflowUtil.getCurrentUsername();
        if (actor == null || actor.isEmpty()) actor = "system";

        String entity = str(properties, "entity");
        String tableName = str(properties, "tableName");
        String statusField = def(str(properties, "statusField"), "status");
        String actionField = def(str(properties, "actionField"), "_action");
        String recordId = str(properties, "recordId");
        if (entity.isEmpty() || tableName.isEmpty() || recordId.isEmpty() || recordId.startsWith("#")) return null;

        FormRow row = dao.load(entity, tableName, recordId);
        if (row == null) return null;
        String action = nz(row.getProperty(actionField));
        if (action.isEmpty()) return null;

        String[] hit = findTransition(str(properties, "transitions"), action);
        if (hit == null) { LogUtil.warn(CN, "no transition for action '" + action + "'"); return null; }
        String target = hit[0];
        String setNowCsv = hit[1];
        String guardExpr = hit[2];
        String startProc = hit[3];

        String result;
        String guardFail = guardExpr.isEmpty() ? null : evalGuard(guardExpr, row);
        try {
            if (guardFail != null)
                throw new InvalidTransitionException(nz(row.getProperty(statusField)), target, guardFail);
            new StatusManager(dao, EVENT_FORM).apply(entity, row, statusField, recordId, target,
                    Collections.<String>emptyList(), actor, action);
            if (!setNowCsv.isEmpty()) {
                String now = LocalDateTime.now().format(TS);
                for (String f : setNowCsv.split(",")) {
                    String fn = f.trim();
                    if (!fn.isEmpty()) row.setProperty(fn, now);
                }
            }
            result = "OK: " + nz(row.getProperty(statusField));
            if (!startProc.isEmpty()) {
                String p = startProcess(startProc, recordId, entity);
                result = result + " · " + p;
            }
        } catch (InvalidTransitionException e) {
            result = "REJECTED: " + e.getMessage();
        } catch (Exception e) {
            result = "ERROR: " + e.getMessage();
            LogUtil.error(CN, e, "transition failed for " + entity + " " + recordId);
        }
        row.setProperty(actionField, "");
        row.setProperty("transition_result", result);
        FormRowSet set = new FormRowSet();
        set.add(row);
        dao.saveOrUpdate(entity, tableName, set);
        LogUtil.info(CN, entity + " " + recordId + " action=" + action + " -> " + result);
        return null;
    }

    /** returns [toState, setNowCsv, guardExpr, startProcessId] for the matching action, or null. */
    private String[] findTransition(String cfg, String action) {
        if (cfg == null) return null;
        for (String seg : cfg.split("\\|")) {
            String[] p = seg.split(">", -1);
            if (p.length >= 2 && action.equals(p[0].trim())) {
                return new String[]{p[1].trim(),
                        p.length > 2 ? p[2].trim() : "",
                        p.length > 3 ? p[3].trim() : "",
                        p.length > 4 ? p[4].trim() : ""};
            }
        }
        return null;
    }

    /**
     * Launches the process a transition declares, binding the record so the activity's form
     * opens on it. Returns a short outcome string that lands in transition_result.
     *
     * Deliberately FAIL-SOFT: the status change is already committed and legal, and refusing
     * to record it because the workflow engine was unhappy would leave the record in a state
     * the lifecycle says it is not in. A failure here means the officer has no task — visible
     * as an empty inbox and caught by the ui-journey leg — not a corrupt record.
     */
    private String startProcess(String processDefId, String recordId, String entity) {
        try {
            AppDefinition appDef = AppUtil.getCurrentAppDefinition();
            if (appDef == null) return "process " + processDefId + " NOT started: no app context";
            WorkflowManager wm = (WorkflowManager)
                    AppUtil.getApplicationContext().getBean("workflowManager");
            if (wm == null) return "process " + processDefId + " NOT started: no workflowManager";
            // packageId:latest:processDefId — 'latest' so a redeployed package version does not
            // strand the caller on an id that no longer resolves.
            String full = appDef.getId() + ":latest:" + processDefId;
            Map<String, String> vars = new HashMap<String, String>();
            vars.put("recordId", recordId);
            vars.put("id", recordId);
            vars.put("entity", entity);
            WorkflowProcessResult r = wm.processStart(full, null, vars, null, recordId, false);
            if (r == null || r.getProcess() == null)
                return "process " + processDefId + " NOT started (engine returned nothing)";
            LogUtil.info(CN, "started " + full + " for " + entity + " " + recordId
                    + " -> instance " + r.getProcess().getInstanceId());
            return "started " + processDefId;
        } catch (Exception e) {                       // noqa: the status move stands regardless
            LogUtil.error(CN, e, "process start failed for " + processDefId + " / " + recordId);
            return "process " + processDefId + " NOT started: " + e.getMessage();
        }
    }

    /**
     * Evaluates a guard predicate of the form {@code <attr> <op> <literal>} against the loaded
     * row, where op is one of {@code eq ne gt lt ge le} (word operators — '>' and '|' are
     * config separators). Numeric comparison when both sides parse as numbers (empty attr
     * value counts as 0); string comparison otherwise (eq/ne only). Returns null when the
     * guard passes, or a human-readable failure message when it blocks the transition.
     * A malformed expression blocks (fail-closed) — a guard that cannot be evaluated must
     * never silently allow the move.
     */
    private String evalGuard(String expr, FormRow row) {
        String[] p = expr.trim().split("\\s+", 3);
        if (p.length != 3) return "guard unparseable: '" + expr + "'";
        String attr = p[0], op = p[1], lit = p[2];
        String raw = nz(row.getProperty(attr)).trim();
        Double a = num(raw.isEmpty() ? "0" : raw), b = num(lit);
        boolean pass;
        if (a != null && b != null) {
            int c = Double.compare(a, b);
            switch (op) {
                case "eq": pass = c == 0; break;
                case "ne": pass = c != 0; break;
                case "gt": pass = c > 0;  break;
                case "lt": pass = c < 0;  break;
                case "ge": pass = c >= 0; break;
                case "le": pass = c <= 0; break;
                default: return "guard unknown operator: '" + op + "'";
            }
        } else {
            switch (op) {
                case "eq": pass = raw.equals(lit);  break;
                case "ne": pass = !raw.equals(lit); break;
                default: return "guard operator '" + op + "' needs numeric operands ('"
                        + raw + "' " + op + " '" + lit + "')";
            }
        }
        return pass ? null : "guard failed: " + expr + " (actual " + attr + "="
                + (raw.isEmpty() ? "<empty>" : raw) + ")";
    }

    private static Double num(String s) {
        try { return Double.valueOf(s); } catch (NumberFormatException e) { return null; }
    }

    private static String str(Map p, String k) { Object v = p.get(k); return v == null ? "" : v.toString(); }
    private static String def(String v, String d) { return v == null || v.isEmpty() ? d : v; }
    private static String nz(String s) { return s == null ? "" : s; }
}
